Reading Data - Read Data from computer machine. 

In [1]:
#import required libraries

import pandas as pd
import numpy as np


In [3]:
#Read Dataset

dataset=pd.read_csv("/50_Startups.csv")

In [5]:
#check top 5 rows

dataset.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

In [7]:
dataset.head(5)

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [9]:
#checking shape of dataset

dataset.shape

(50, 5)

**Define Input Outfut Features and Featuring Engineering**

In [25]:
#Defining inpur fiture X and output feature y

X= dataset.iloc[:,:-1].values
y= dataset.iloc[:, -1].values

In [14]:
#check the shape of input and output features

print(f'The shape of input feature : {X.shape}')
print(f"The shape of output feature : {y.shape}")


The shape of input feature : (50, 4)
The shape of output feature : (50,)


In [26]:
#checking input matrix

print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

As there are categorical values present in the city column of the dataset, we need to perform categorical encoding. For this purpose, the one-hot encoding method is suitable as the categories here are nominal.



In [27]:
 # Onehot encoding for categorical column

 from sklearn.compose import ColumnTransformer
 from sklearn.preprocessing import OneHotEncoder

 #ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[3])], remainder= "passthrough"])

 ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')

 X=np.array(ct.fit_transform(X))


In [28]:
#input feature matrix after categorical encoding

print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [31]:
#Spliting inputs into Training and Test Sets

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test= train_test_split(X,y,test_size= 0.2, random_state=0)

In [32]:
#Checking shape of Train and test dataset

print(f'shape of training pattern is : {X_train.shape, y_train.shape}')
print(f'shape of testuiung pattern is :{X_test.shape, y_test.shape}')

shape of training pattern is : ((40, 6), (40,))
shape of testuiung pattern is :((10, 6), (10,))


**Step 3: Defining and training the multiple linear regression model**

In [34]:
# Defining a linear regression model
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [35]:
# Fitting the linear regression model

regressor.fit(X_train, y_train)

LinearRegression()

In [36]:
# Checking the regression coefficients of the fitted model


print('The regression coefficients are:', regressor.coef_)

The regression coefficients are: [ 8.66383692e+01 -8.72645791e+02  7.86007422e+02  7.73467193e-01
  3.28845975e-02  3.66100259e-02]


In [37]:
# Checking the intercept

print('The intercept', regressor.intercept_)

The intercept 42467.52924853204


**Step 4: Making predictions with the trained model**

In [39]:
#Making predictions on the test data

y_pred = regressor.predict(X_test)

In [40]:
# Comparing the predicted profit with actual profit
pd.DataFrame(data={'Predicted Profit': y_pred, 'Actual Profit': y_test})

Predicted Profit  Actual Profit
0     103015.201598      103282.38
1     132582.277608      144259.40
2     132447.738452      146121.95
3      71976.098513       77798.83
4     178537.482211      191050.39
5     116161.242302      105008.31
6      67851.692097       81229.06
7      98791.733747       97483.56
8     113969.435330      110352.25
9     167921.065696      166187.94

**Step 5: Evaluate the prediction performance**

In [41]:
# Mean Squared Error (MSE)

from sklearn.metrics import mean_squared_error

MSE=mean_squared_error(y_test, y_pred)
print('Mean Squared Error is:', MSE)

Mean Squared Error is: 83502864.03256583


In [42]:
# Root Mean Squared Error (RMSE)

import math
RMSE = math.sqrt(MSE)
print('Root Mean Squared Error is:', RMSE)

Root Mean Squared Error is: 9137.990152794313


In [43]:
# R-Squared

from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
print('R-Squared is:', r2)

R-Squared is: 0.9347068473282515


In [44]:
 #Adjusted R-Squared
 
adj = 1-(
         (1-r2)*(X_train.shape[0]-1)/
          (X_train.shape[0]-X_train.shape[1]-1)
          )
print('Adjusted R-Squared is:', adj)

Adjusted R-Squared is: 0.9228353650242972
